name: Use Docker Action

on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Container action
        uses: ./
        with:
          name: Ben
